// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMs_dt5YZi30WBddk5lY5J3lBQOnTbSs',
    appId: '1:144402484766:web:768c5f3bac2ebe9637680f',
    messagingSenderId: '144402484766',
    projectId: 'weather-8731f',
    authDomain: 'weather-8731f.firebaseapp.com',
    storageBucket: 'weather-8731f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtsReGCrqmfGMYuOQ2qlCn6TPbEXfTjOk',
    appId: '1:144402484766:android:69ae0036a9a0bc0937680f',
    messagingSenderId: '144402484766',
    projectId: 'weather-8731f',
    storageBucket: 'weather-8731f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tPO29ijsvPalZUDj2Dyy7oeuGhjZmLw',
    appId: '1:144402484766:ios:087293ba6099385a37680f',
    messagingSenderId: '144402484766',
    projectId: 'weather-8731f',
    storageBucket: 'weather-8731f.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tPO29ijsvPalZUDj2Dyy7oeuGhjZmLw',
    appId: '1:144402484766:ios:02d527f41d34661d37680f',
    messagingSenderId: '144402484766',
    projectId: 'weather-8731f',
    storageBucket: 'weather-8731f.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
